
#FROM python:3.12.7-alpine3.20
#WORKDIR /project
#COPY . /project
#RUN pip3 install requests
#CMD ["python3", "home_work.py"]



#FROM python:3.12.7-alpine3.20 # Базовый образ
#RUN mkdir /project
#WORKDIR /project # Рабочая директория внутри образа
#COPY . /project # Копируем все файлы в образ
#RUN pip3 install requests # Устанавливаем requests для api тестов
#CMD ["python3", "home_work.py"]  # Команда запуска программы

FROM python:3.12.0a4-alpine3.17
# Установка Allure
RUN apk update && \
    apk add openjdk11-jre curl tar && \
    curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz && \
    tar -zxvf allure-2.13.8.tgz -C /opt/ && \
    ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure && \
    rm allure-2.13.8.tgz

WORKDIR /project
COPY ./requirements.txt /project
RUN pip3 install -r requirements.txt



